name: yourfit
description: App submission for 2024 Congressional App Challenge.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.4.3

dependencies:
  table_calendar: ^3.0.0

  flutter:
    sdk: flutter
  envied: ^0.5.4+1
  flutter_contacts: ^1.1.9+2
  supabase_flutter:
  get_it: ^8.0.0
  intl:
  injectable: ^2.5.0
  google_sign_in: ^6.2.1
  async_button_builder: ^3.0.0+1
  sign_in_with_apple: ^6.1.3
  auto_route: ^9.2.2
  typewritertext: ^3.0.9
  ffi: ^2.1.3
  nice_buttons: ^0.0.3
  zod_validation: ^1.0.5
  flutter_focus_watcher: ^2.0.0
  animated_snack_bar: ^0.4.0
  langchain: ^0.7.7+1
  langchain_core: ^0.3.6
  langchain_community: ^0.3.2+1
  langchain_openai: ^0.7.2+3
  langchain_supabase: ^0.1.1+3
  langchain_mistralai: ^0.2.3+1
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1
  groq:
  mistralai_client_dart: ^1.0.0
  onboarding: ^4.0.2
  flutter_animation_progress_bar: ^2.3.1
  text_wrap_auto_size: ^1.2.3
  path_provider: ^2.1.4
  provider: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.12
  envied_generator: ^0.5.4+1
  auto_route_generator: ^9.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          style: normal
          weight: 100

    - family: Lilita
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
          style: normal
          weight: 100